@tool
extends Object
class_name AudioRegistry

# --- GENERATED BY AUDIODASHBOARD (DO NOT EDIT MANUALLY) ---

const SLUGS = {
	"music": "uid://b4upwqc5bu5s5",
	"fuse": "uid://h6urv1g40s73",
	"shape_bounce": "uid://bkw1c5ne3d5xh",
	"wet_click": "uid://b7dfx1elcb0xa",
}
